name: ea-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  # Core scientific python
  - numpy
  - matplotlib
  - pyqt
  - seaborn

  # Spatial packages
  - descartes # for geopandas until they release
  - rasterstats
  - geopy
  - cartopy
  - contextily
  - earthpy
  - folium
  - geojson
  - mapboxgl
  - hydrofunctions
  - geocoder
  - tweepy
  - rioxarray
  - scipy
  - netcdf4
  - nc-time-axis
  - regionmask

  # Natural language processing
  - nltk
  - textblob

  # Jupyter Environment
  - papermill
  - notebook
  - ipython
  # Autograding
  - matplotcheck>=0.1.2
